### ISSUE TITLE
pytest-xdist is required

### ISSUE THREAD

**Issue by vquilon** [blake-r/pytest-durations#3]
Hi, I start using pytest, and I installed pytest_durations plugins, but I got this error
```
platform win32 -- Python 3.7.11, pytest-7.0.1, pluggy-1.0.0
rootdir: ...\rootdir, configfile: pytest.ini
plugins: cov-3.0.0, custom-report-1.0.1, durations-1.0.1, excel-1.5.0
collected 1 item
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\...\lib\site-packages\_pytest\main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "D:\...\lib\site-packages\_pytest\main.py", line 321, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "D:\...\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "D:\...\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "D:\...\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\...\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "D:\...\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\...\lib\site-packages\_pytest\main.py", line 332, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "D:\...\lib\site-packages\_pytest\main.py", line 659, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "D:\...\lib\site-packages\pluggy\_manager.py", line 265, in check_pending
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> pluggy._manager.PluginValidationError: unknown hook 'pytest_testnodedown' in plugin <pytest_durations.plugin.Pyte
stDurationPlugin object at 0x000002740A822FC8>

==================================================== 9 warnings in 22.15s ===================================================== 
```

I found in other pytest plugin the same issue

- [pytest-xdist is required](https://github.com/pytest-dev/pytest-splinter/issues/13)

So its now executed well if install the xdist package:
`pip install pytest-xdist`

Shit happens sometimes, I see you upload a new version recent, typically environments failures.

**Comment by blake-r** [comment]
Thank you for reporting!

It is fixed in the version 1.1.0 now.

Have a good day!
